import React from "react";
import {
  ArrowRightIcon,
  ArrowPathIcon,
  FlagIcon,
  ComputerDesktopIcon,
  KeyboardIcon,
  ChatBubbleLeftIcon,
  LightBulbIcon,
  EyeIcon,
  EyeSlashIcon,
  ArrowsPointingOutIcon,
  ClockIcon,
  ArrowPathRoundedSquareIcon,
  TrashIcon,
  PlusIcon,
  PlayIcon,
  StopIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowUturnLeftIcon,
  ArrowUturnRightIcon,
  ArrowPathIcon as RepeatIcon,
  ArrowTrendingUpIcon,
  ArrowTrendingDownIcon,
  ArrowUpOnSquareIcon,
  ArrowDownOnSquareIcon,
  ArrowLeftOnRectangleIcon,
  ArrowRightOnRectangleIcon,
  ArrowTopRightOnSquareIcon,
  ArrowDownTrayIcon,
  ArrowUpTrayIcon,
  ArrowLongLeftIcon,
  ArrowLongRightIcon,
  ArrowLongUpIcon,
  ArrowLongDownIcon,
  ArrowUpCircleIcon,
  ArrowDownCircleIcon,
  ArrowLeftCircleIcon,
  ArrowRightCircleIcon,
  ArrowUpLeftIcon,
  ArrowUpRightIcon,
  ArrowDownLeftIcon,
  ArrowDownRightIcon,
  ArrowSmallLeftIcon,
  ArrowSmallRightIcon,
  ArrowSmallUpIcon,
  ArrowSmallDownIcon,
  ArrowUturnUpIcon,
  ArrowUturnDownIcon,
  ArrowPathIcon as RefreshIcon,
  ArrowPathIcon as RotateIcon,
  CursorArrowRaysIcon,
  CommandLineIcon,
} from "@heroicons/react/24/solid";

const iconMap = {
  "arrow-right": ArrowRightIcon,
  "rotate-right": ArrowPathIcon,
  "flag": FlagIcon,
  "mouse": CursorArrowRaysIcon,
  "keyboard": CommandLineIcon,
  "comment": ChatBubbleLeftIcon,
  "thought": LightBulbIcon,
  "eye": EyeIcon,
  "eye-off": EyeSlashIcon,
  "resize": ArrowsPointingOutIcon,
  "clock": ClockIcon,
  "infinity": ArrowPathRoundedSquareIcon,
  "trash": TrashIcon,
  "plus": PlusIcon,
  "play": PlayIcon,
  "stop": StopIcon,
  "target": ArrowUpOnSquareIcon,
  "repeat": ArrowPathRoundedSquareIcon,
  "move": ArrowRightIcon,
  "arrow-up": ArrowUpIcon,
  "arrow-down": ArrowDownIcon,
  "arrow-left": ArrowLeftIcon,
  "arrow-uturn-left": ArrowUturnLeftIcon,
  "arrow-uturn-right": ArrowUturnRightIcon,
  "refresh": RefreshIcon,
  "rotate": RotateIcon,
  "arrow-trending-up": ArrowTrendingUpIcon,
  "arrow-trending-down": ArrowTrendingDownIcon,
  "arrow-up-on-square": ArrowUpOnSquareIcon,
  "arrow-down-on-square": ArrowDownOnSquareIcon,
  "arrow-left-on-rectangle": ArrowLeftOnRectangleIcon,
  "arrow-right-on-rectangle": ArrowRightOnRectangleIcon,
  "arrow-top-right-on-square": ArrowTopRightOnSquareIcon,
  "arrow-down-tray": ArrowDownTrayIcon,
  "arrow-up-tray": ArrowUpTrayIcon,
  "arrow-long-left": ArrowLongLeftIcon,
  "arrow-long-right": ArrowLongRightIcon,
  "arrow-long-up": ArrowLongUpIcon,
  "arrow-long-down": ArrowLongDownIcon,
  "arrow-up-circle": ArrowUpCircleIcon,
  "arrow-down-circle": ArrowDownCircleIcon,
  "arrow-left-circle": ArrowLeftCircleIcon,
  "arrow-right-circle": ArrowRightCircleIcon,
  "arrow-up-left": ArrowUpLeftIcon,
  "arrow-up-right": ArrowUpRightIcon,
  "arrow-down-left": ArrowDownLeftIcon,
  "arrow-down-right": ArrowDownRightIcon,
  "arrow-small-left": ArrowSmallLeftIcon,
  "arrow-small-right": ArrowSmallRightIcon,
  "arrow-small-up": ArrowSmallUpIcon,
  "arrow-small-down": ArrowSmallDownIcon,
  "arrow-uturn-up": ArrowUturnUpIcon,
  "arrow-uturn-down": ArrowUturnDownIcon,
};

export default function Icon({ name, size = 20, className = "" }) {
  const IconComponent = iconMap[name];
  if (!IconComponent) {
    console.warn(`Icon "${name}" not found`);
    return null;
  }
  return <IconComponent className={className} style={{ width: size, height: size }} />;
}
